[package]
name = "finally-block"
version = "0.1.0"
authors = ["Seulgi Kim <seulgi.kim@kodebox.io>"]
edition = "2018"
license = "MIT"
repository = "http://github.com/CodeChain-io/rust-finally-block"
keywords = ["control", "raii", "finally", "block"]

[dependencies]
